name: Deepstone
version: '0.8'
main: fr.deepstonestudio.deepstone.Deepstone
api-version: '1.21'
authors: [ Deepstone-Studio ]
softdepend:
  - PlaceholderAPI
  - Essentials

commands:
  clan:
    description: Gestion des clans Deepstone
    usage: /clan help
  clearlag:
    description: Force le nettoyage des items au sol
    usage: /clearlag



permissions:
  deepstone.clan.admin:
    default: op

  deepstone.clearlag:
    description: Autorise /clearlag
    default: op

  deepstone.pl:
    description: Autorise l'utilisation de /pl
    default: op

  deepstone.afk.bypass:
    description: Ne passe jamais AFK via DeepstoneAFK (mode sans Essentials).
    default: op

  deepstone.afk.kickexempt:
    description: Immunisé contre l'auto-kick AFK via DeepstoneAFK (mode sans Essentials).
    default: op
  deepstone.rembourse:
    description: Permissions modérateur
    default: op

